apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: mcg-osd-deployer-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcg-osd-deployer-proxy-role
subjects:
- kind: ServiceAccount
  name: mcg-osd-deployer-controller-manager
  namespace: redhat-data-federation
