apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: mcg-osd-deployer-kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcg-osd-deployer-proxy-role
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: redhat-data-federation
