apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "mcg.openshift.io/v1alpha1",
          "kind": "ManagedMCG",
          "metadata": {
            "name": "managedmcg-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    console.openshift.io/plugins: '["mcg-ms-console"]'
    operators.operatorframework.io/builder: operator-sdk-v1.18.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: mcg-osd-deployer.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ManagedMCG is the Schema for the managedmcgs API.
      displayName: Managed MCG
      kind: ManagedMCG
      name: managedmcgs.mcg.openshift.io
      version: v1alpha1
  description: Installs and manages ManagedMCG instance on OpenShiftDedicated clusters.
  displayName: MCG OSD Deployer
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - console.openshift.io
          resources:
          - consoleplugins
          verbs:
          - '*'
        - apiGroups:
          - mcg.openshift.io
          resources:
          - managedmcgs
          - managedmcgs/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - mcg.openshift.io
          resources:
          - managedmcgs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - objectbucket.io
          resources:
          - objectbucketclaims
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - operator.openshift.io
          resources:
          - consoles
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        serviceAccountName: deployer
      deployments:
      - name: mcg-osd-deployer-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy:
            type: Recreate
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
                livenessProbe:
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  tcpSocket:
                    port: 8443
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                readinessProbe:
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  tcpSocket:
                    port: 8443
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/osd-addons/mcg-osd:0.1.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8082
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8082
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 200Mi
                  requests:
                    cpu: 100m
                    memory: 200Mi
              - command:
                - /readinessServer
                env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/osd-addons/mcg-osd:0.1.0
                livenessProbe:
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  tcpSocket:
                    port: 8081
                name: readiness-server
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 30Mi
              securityContext:
                runAsNonRoot: true
              serviceAccountName: deployer
              terminationGracePeriodSeconds: 10
      - name: mcg-ms-console
        spec:
          selector:
            matchLabels:
              app: mcg-ms-console
          strategy: {}
          template:
            metadata:
              labels:
                app: mcg-ms-console
            spec:
              containers:
              - image: quay.io/osd-addons/mcg-ms-console-dev:latest
                livenessProbe:
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  tcpSocket:
                    port: 9002
                name: mcg-ms-console
                ports:
                - containerPort: 9002
                  protocol: TCP
                readinessProbe:
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  tcpSocket:
                    port: 9002
                resources:
                  limits:
                    cpu: 100m
                    memory: 512Mi
                  requests:
                    cpu: 100m
                    memory: 512Mi
                volumeMounts:
                - mountPath: /var/serving-cert
                  name: mcg-ms-console-serving-cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              tolerations:
              - effect: NoSchedule
                key: node.ocs.openshift.io/storage
                operator: Equal
                value: "true"
              volumes:
              - name: mcg-ms-console-serving-cert
                secret:
                  secretName: mcg-ms-console-serving-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - endpoints
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - alertmanagerconfigs
          - alertmanagers
          - prometheuses
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - podmonitors
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheusrules
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - noobaa.io
          resources:
          - backingstores
          verbs:
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - noobaa.io
          resources:
          - bucketclasses
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - noobaa.io
          resources:
          - namespacestores
          verbs:
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - noobaa.io
          resources:
          - noobaas
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - objectbucket.io
          resources:
          - objectbucketclaims
          verbs:
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - objectbucket.io
          resources:
          - objectbucketclaims/finalizers
          verbs:
          - update
        - apiGroups:
          - operators.coreos.com
          resources:
          - clusterserviceversions
          verbs:
          - delete
          - get
          - list
          - update
          - watch
        serviceAccountName: deployer
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  keywords:
  - managed services
  - ms
  - noobaa
  - deployer
  - addon
  - operator
  - mcg
  - multicloud gateway
  links:
  - name: Mcg Osd Deployer
    url: https://github.com/red-hat-storage/mcg-osd-deployer
  maintainers:
  - email: prasriva@redhat.com
    name: Pranshu Srivastava
  - email: napaul@redhat.com
    name: Naveen Paul
  maturity: alpha
  provider:
    name: Red Hat
  version: 1.0.0
