apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: mcg-osd-deployer-k8s-metrics-sm-prometheus-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcg-osd-deployer-k8s-metrics-sm-prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: redhat-data-federation
