# permissions for end users to edit managedmcgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedmcg-editor-role
rules:
- apiGroups:
  - mcg.openshift.io
  resources:
  - managedmcgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcg.openshift.io
  resources:
  - managedmcgs/status
  verbs:
  - get
