MCG_CONSOLE_IMG_NAME ?= mcg-ms-console-dev
MCG_CONSOLE_IMG_TAG ?= latest
MCG_CONSOLE_IMG_LOCATION ?= quay.io/osd-addons
MCG_CONSOLE_IMG ?= $(MCG_CONSOLE_IMG_LOCATION)/$(MCG_CONSOLE_IMG_NAME):$(MCG_CONSOLE_IMG_TAG)
