#!/bin/sh

# Check if go is installed
if ! command -v go >/dev/null 2>&1; then
  echo "go is not installed"
  exit 1
fi

# Check if $GOBIN is set
if [ -z "$(go env GOBIN)" ]; then
  echo "GOBIN is not set"
  exit 1
fi

# Check if golangci-lint binary is available
if ! command -v golangci-lint > /dev/null; then
  echo "golangci-lint is not installed, installing..."
  # Fetch golangci-lint binary
  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOBIN)" v1.45.2
fi

echo "[Running golangci-lint]"
PROJECT_ROOT=$(realpath "$(dirname "$0")"/../../)
golangci-lint -c "$PROJECT_ROOT"/.golangci.yaml run "$PROJECT_ROOT"/...
