#!/bin/sh

PROJECT_ROOT=$(realpath "$(dirname "$0")"/../../)
GOLANGCI_LINT_PATH="$PROJECT_ROOT/hack/hooks/golangci-lint"

# Check if go is installed
if ! command -v go >/dev/null 2>&1; then
  echo "go is not installed"
  exit 1
fi

# Check if $GOBIN is set
if [ -z "$(go env GOBIN)" ]; then
  echo "GOBIN is not set, using GOPATH/bin"
  GOBIN=$(go env GOPATH)/bin
  export GOBIN
fi

echo "[Running golangci-lint]"
${GOLANGCI_LINT_PATH} -c "$PROJECT_ROOT"/.golangci.yaml run "$PROJECT_ROOT"/...

